# Generated by Django 5.0.14 on 2026-04-19 04:14

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('contenido', models.TextField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='noticias/')),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Aviso / Noticia',
                'verbose_name_plural': 'Tablero de Avisos',
                'ordering': ['-fecha_publicacion'],
            },
        ),
        migrations.CreateModel(
            name='Pipa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_economico', models.CharField(help_text='Ej. PIPA-04', max_length=50, unique=True)),
                ('capacidad_litros', models.IntegerField(default=10000)),
                ('chofer', models.CharField(blank=True, max_length=100)),
                ('estado', models.CharField(choices=[('DISPONIBLE', '🟢 Disponible'), ('EN_RUTA', '🚚 En Ruta / Trabajando'), ('TALLER', '🔴 En Mantenimiento')], default='DISPONIBLE', max_length=20)),
                ('ubicacion_actual', django.contrib.gis.db.models.fields.PointField(blank=True, help_text='Ubicación GPS en tiempo real', null=True, srid=4326)),
            ],
            options={
                'verbose_name': 'Unidad (Pipa)',
                'verbose_name_plural': 'Inventario de Pipas',
            },
        ),
        migrations.CreateModel(
            name='Pozo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('ubicacion', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('estado', models.CharField(default='OPERATIVO', max_length=20)),
                ('profundidad', models.DecimalField(blank=True, decimal_places=2, help_text='Profundidad en metros', max_digits=6, null=True)),
                ('notas', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Pozo',
                'verbose_name_plural': 'Infraestructura de Pozos',
            },
        ),
        migrations.CreateModel(
            name='PerfilCiudadano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colonia', models.CharField(blank=True, max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Ciudadano',
                'verbose_name_plural': 'Perfiles de Ciudadanos',
            },
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(editable=False, max_length=20, null=True, unique=True)),
                ('tipo_problema', models.CharField(choices=[('FUGA', 'Fuga de Agua'), ('ESCASEZ', 'Escasez / No hay agua'), ('CALIDAD', 'Mala Calidad / Agua Sucia'), ('ALCANTARILLADO', 'Falla en Drenaje/Alcantarilla'), ('TRAMITE', 'Solicitud de Trámite')], max_length=20)),
                ('descripcion', models.TextField(help_text='Descripción detallada del problema')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='reportes/')),
                ('ubicacion', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('direccion_texto', models.CharField(blank=True, help_text='Calle y Número aproximado', max_length=255)),
                ('status', models.CharField(choices=[('PENDIENTE', 'Recibido / Pendiente'), ('ASIGNADO', 'Asignado a Cuadrilla'), ('EN_PROCESO', 'En Reparación'), ('RESUELTO', 'Concluido'), ('CANCELADO', 'Improcedente')], default='PENDIENTE', max_length=20)),
                ('prioridad', models.IntegerField(default=0, help_text='Calculado automáticamente basado en validaciones')),
                ('validaciones', models.IntegerField(default=0, help_text='Número de vecinos que han confirmado este reporte')),
                ('nota_seguimiento', models.TextField(blank=True, help_text='Respuesta oficial o bitácora de trabajo')),
                ('foto_solucion', models.ImageField(blank=True, null=True, upload_to='soluciones/')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('pipa_asignada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicios', to='api.pipa')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitud Ciudadana',
                'verbose_name_plural': 'Solicitudes de Servicio',
                'ordering': ['-fecha_hora'],
            },
        ),
        migrations.CreateModel(
            name='Validacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_voto', models.DateTimeField(auto_now_add=True)),
                ('reporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votos', to='api.reporte')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Validación Vecinal',
                'verbose_name_plural': 'Validaciones',
                'unique_together': {('reporte', 'usuario')},
            },
        ),
    ]
